openapi: 3.0.0
info:
  title: Cart API
  version: 1.0.0
  description: API for managing carts
paths:
  /api/carts:
    get:
      summary: Get all carts
      tags:
        - Carts
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cart'
    post:
      summary: Create a new cart
      tags:
        - Carts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CartInput'
      responses:
        '201':
          description: Cart created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
  /api/carts/{cid}:
    get:
      summary: Get a cart by ID
      tags:
        - Carts
      parameters:
        - name: cid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        '404':
          description: Cart not found
    put:
      summary: Update a cart by ID
      tags:
        - Carts
      parameters:
        - name: cid
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CartInput'
      responses:
        '200':
          description: Cart updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        '404':
          description: Cart not found
    delete:
      summary: Delete a cart by ID
      tags:
        - Carts
      parameters:
        - name: cid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Cart deleted successfully
        '404':
          description: Cart not found
  /api/carts/{cid}/product/{pid}:
    post:
      summary: Add a product to a cart
      tags:
        - Carts
      parameters:
        - name: cid
          in: path
          required: true
          schema:
            type: string
        - name: pid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Product added to cart successfully
        '404':
          description: Cart or Product not found
    delete:
      summary: Remove a product from a cart
      tags:
        - Carts
      parameters:
        - name: cid
          in: path
          required: true
          schema:
            type: string
        - name: pid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Product removed from cart successfully
        '404':
          description: Cart or Product not found

components:
  schemas:
    Cart:
      type: object
      properties:
        _id:
          type: string
        userId:
          type: string
        products:
          type: array
          items:
            $ref: '#/components/schemas/CartProduct'
    CartProduct:
      type: object
      properties:
        productId:
          type: string
        quantity:
          type: number
    CartInput:
      type: object
      properties:
        userId:
          type: string
        products:
          type: array
          items:
            $ref: '#/components/schemas/CartProductInput'
    CartProductInput:
      type: object
      properties:
        productId:
          type: string
        quantity:
          type: number
